### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by Sodak**
I hope this works with the pull request. its added a custom ammo entity

### CODE REVIEW

**Comment by fnoah** [comment]
May I ask, why you add a blank character in front of almost every exclamation mark?

**Comment by Guilhem-Pech** [comment]
@fnoah because it's the french standard and we forgot that in english/or some other language we don't do that ^^'

**Comment by fnoah** [comment]
@Guilhem-Pech I see. Should I change it?

**Comment by Guilhem-Pech** [comment]
You can make a pull request with the modifications if you want

**Pull request merged**
