### PR TITLE
Add "category" field in gamemode text file

### PR DESCRIPTION
**Pull request by KurimuzonAkuma**

### CODE REVIEW

**Review by Guilhem-Pech — COMMENTED** [review]
Not really sure we could say that slashers is a RP gamemode haha
What are the available categories?

**Comment by KurimuzonAkuma** [comment]
> Not really sure we could say that slashers is a RP gamemode haha What are the available categories?

Roleplay, PvP, PvE, Other and uncategorized

**Comment by KurimuzonAkuma** [comment]
Yes, I think you're right. It would be better to put "pvp" instead

**Comment by Guilhem-Pech** [comment]
Thanks :)

**Pull request merged**
